### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by hdgarrood** [purescript-node/purescript-node-child-process#1]
@joneshf: I just pushed your repository to here - sorry for being impatient.

I just noticed there's no license. Would you be ok with MIT? Is assigning copyright to PureScript ok?

**Comment by paf31** [comment]
I think it would be nice to be able to reuse the work done here, so if the license could be clarified, that would be great. But we shouldn't redistribute code with no explicit license from `purescript-node`.

Copyright assignment isn't necessary either really. In the compiler, I try to arrange things so that contributors keep copyright and just license code to us for reuse. So in that sense, if the original code is licensed permissively, we can keep the original copyright notice and everything's good.

**Comment by hdgarrood** [comment]
Ah yes, of course, sorry. Should I take this down for now then?

There was no license file originally, but it did say "license": "MIT" inside the package.json.

**Comment by joneshf** [comment]
Either way works. Just let me know what I need to do, if anything.

**Comment by hdgarrood** [comment]
In a4b0e74, I uploaded a copy of the MIT license into this repository, with you as the copyright holder, so nobody needs to do anything now :) unless, of course, you want to change anything about how it's licensed.
